// Editorial content is independent of the shared, server-rendered service template.
const image = (file, alt) => ({ src: `/images/${file}.webp`, alt: `Illustrative ${alt}`, width: 800, height: 800 });
export const buildings = {
  commercial: { title: 'Commercial', image: image('sector-0', 'glass-fronted office building') },
  industrial: { title: 'Industrial', image: image('sector-1', 'metal-clad industrial building') },
  heritage: { title: 'Heritage', href: '/services/heritage-building-cleaning', image: image('service-roof', 'traditional stone building with a slate roof') },
  retail: { title: 'Retail buildings', image: image('service-signage', 'retail fascia and external signage') },
  glazing: { title: 'Glazed façades', href: '/services/window-glass-cleaning', image: image('service-windows', 'external office glazing') },
  solar: { title: 'Rooftop arrays', href: '/services/solar-panel-cleaning', image: image('service-solar', 'rooftop solar panels') },
  render: { title: 'Rendered elevations', href: '/services/render-cleaning', image: image('service-render', 'textured rendered exterior') },
};
export const services = [
  {
    slug: 'facade-cleaning', title: 'Façade cleaning', seoTitle: 'Façade Cleaning | DroneReach',
    meta: 'Drone-powered façade cleaning for commercial, industrial and heritage buildings. An assessed, tailored approach to exterior cleaning. Request a quote from DroneReach.',
    description: 'Drone-powered cleaning for commercial, industrial and heritage buildings.',
    summary: 'A tailored approach to dirt, algae and surface staining across mixed-material building exteriors.',
    image: image('sector-0', 'glass-fronted commercial building façade'),
    hero: { src: '/images/hero.webp', alt: 'Illustrative drone cleaning a glass building façade', width: 1200, height: 900 },
    benefits: ['Less work at height', 'Less disruption', 'A tailored clean'],
    heading: 'A cleaner exterior. A lasting impression.',
    introduction: 'Dirt, algae and surface staining can leave your building looking tired. We tailor the cleaning method to your façade’s material and condition, helping improve its appearance while keeping disruption to a minimum.',
    checklist: ['Metal cladding', 'Glass & glazing', 'Masonry & stone', 'Hard-to-reach elevations'],
    support: 'Suitability and expected results confirmed following assessment.',
    buildings: ['commercial', 'industrial', 'heritage'],
    faqs: [
      ['Is my building suitable for drone cleaning?', 'Suitability depends on the building’s height, materials, condition and surroundings. We assess the site before recommending a cleaning approach.'],
      ['Could cleaning damage the façade?', 'An unsuitable cleaning method can damage a surface. We assess the material and condition, select an appropriate approach and identify where a test area is needed before proceeding.'],
      ['Will the building need to close during cleaning?', 'Some buildings may remain in use, although temporary exclusion zones or access restrictions may be needed. We agree these arrangements with you before work starts.'],
      ['Do you need access to water on site?', 'We confirm water and access requirements during the assessment so you know what needs to be available before the cleaning day.'],
      ['How is the price calculated?', 'Pricing depends on the area, surface material, condition, access and site requirements. Share the building’s location and a few photos to help us assess the work.'],
    ],
  },
  {
    slug: 'cladding-cleaning', title: 'Cladding cleaning', seoTitle: 'Commercial Cladding Cleaning | DroneReach',
    meta: 'Cleaning for metal and coated cladding on commercial and industrial buildings. DroneReach assesses panel condition and finish before recommending a method.',
    description: 'Cleaning for commercial and industrial cladding, with the finish and condition assessed first.',
    summary: 'Remove surface dirt and organic growth from metal and coated panels with a finish-sensitive approach.',
    image: image('sector-1', 'metal-clad industrial building'),
    benefits: ['Finish-led assessment', 'Targeted panel cleaning', 'Planned site access'],
    heading: 'Care for the finish. Refresh the building.',
    introduction: 'Dirt and organic growth can collect on exposed cladding. We assess the panel material, coating, joints and existing condition before proposing a cleaning method for your commercial or industrial exterior.',
    checklist: ['Metal wall panels', 'Coated cladding', 'Warehouse elevations', 'Industrial façades'],
    support: 'Existing damage, loose panels or failing coatings may need attention before cleaning.',
    buildings: ['industrial', 'commercial', 'retail'],
    faqs: [
      ['Can you clean coated metal panels?', 'We first identify the coating and its condition. Product guidance, signs of wear and any test-area requirements inform the method; not every coating will be suitable.'],
      ['Will cleaning restore a faded finish?', 'Cleaning can address surface contamination, but it cannot repair fading, corrosion or coating failure. We discuss those limitations during assessment.'],
      ['How do you protect panel joints?', 'We review joints, fixings and signs of water ingress before planning the work. Vulnerable areas may need repair or a different approach.'],
      ['Can cleaning fit around warehouse operations?', 'We discuss delivery routes, working hours and exclusion zones with you. The agreed plan sets out any access restrictions before cleaning begins.'],
    ],
  },
  {
    slug: 'roof-cleaning', title: 'Roof cleaning', seoTitle: 'Commercial Roof Cleaning | DroneReach',
    meta: 'Assessment-led roof cleaning for commercial and large buildings. DroneReach reviews roof material, condition, access and method before confirming suitability.',
    description: 'Assessment-led cleaning for commercial and large-building roofs. Suitability comes first.',
    summary: 'Roof cleaning planned around the material, condition and access requirements of each building.',
    image: { src: '/images/service-commercial-roof.webp', alt: 'Illustrative metal roof of a large industrial warehouse', width: 1200, height: 800 },
    benefits: ['Material-led methods', 'Access assessed first', 'Clear scope of work'],
    heading: 'The right approach for your roof.',
    introduction: 'Commercial roofs vary widely in construction and condition. We review the roof material, surface contamination, drainage, access and surrounding site before proposing a method. Drone cleaning is an option on suitable jobs, not a solution for every roof.',
    checklist: ['Commercial roof areas', 'Large industrial roofs', 'Suitable metal roof surfaces', 'Difficult-access roof sections'],
    support: 'Fragile, damaged or sensitive roofs may require a different method or specialist attention.',
    buildings: ['industrial', 'commercial', 'solar'],
    faqs: [
      ['Can every roof be cleaned by drone?', 'No. Roof material, pitch, condition, access, weather and the proposed cleaning method all affect suitability. We confirm what is appropriate after assessment.'],
      ['What if the roof is fragile or damaged?', 'We identify visible concerns and discuss any further inspection or repairs needed. Cleaning should not proceed where the proposed approach could compromise the roof.'],
      ['Does cleaning include roof repairs?', 'Roof cleaning does not include structural repairs or replacement of damaged roofing. We keep the cleaning scope and any separate maintenance needs clear.'],
      ['How are runoff and surrounding areas considered?', 'We review drainage, nearby equipment, occupied areas and site requirements as part of the plan. Any controls and access restrictions are agreed before work.'],
    ],
  },
  {
    slug: 'window-glass-cleaning', title: 'Window & glass cleaning', seoTitle: 'External Window & Glass Cleaning | DroneReach',
    meta: 'External window and glass cleaning for commercial buildings, glazed façades and difficult-to-reach glazing. Request an assessed cleaning plan from DroneReach.',
    description: 'Exterior glazing and difficult-to-reach windows, cleaned with a method suited to the building.',
    summary: 'A considered approach to external windows, glazed façades and high-level glass.',
    image: image('service-windows', 'tall glass office windows'),
    benefits: ['High-level access options', 'Glazing-aware methods', 'Site disruption planned'],
    heading: 'A clearer view of your building.',
    introduction: 'External glazing collects dirt and weather-related deposits. We assess the glass, frames, seals and access requirements to select a cleaning approach for your office windows or glazed façade, including areas that are difficult to reach conventionally.',
    checklist: ['External office windows', 'Glazed building façades', 'High-level glazing', 'Retail exterior glass'],
    support: 'Special coatings, damaged seals and persistent deposits may require additional assessment.',
    buildings: ['commercial', 'glazing', 'retail'],
    faqs: [
      ['Do you clean internal windows?', 'This service focuses on external windows and glass. Share the areas you need cleaned so we can confirm the scope.'],
      ['Can you clean glass with specialist coatings?', 'We need to identify the coating and any manufacturer guidance before selecting a method. Some glass may need a specialist approach.'],
      ['Will cleaning remove scratches or etched marks?', 'Cleaning does not repair scratches or etched glass. We assess deposits and staining separately and discuss what results are realistic.'],
      ['How do you work around entrances and occupied offices?', 'We agree access arrangements, exclusion zones and timing before work. The plan takes account of people using the building and surrounding areas.'],
    ],
  },
  {
    slug: 'solar-panel-cleaning', title: 'Solar panel cleaning', seoTitle: 'Commercial Solar Panel Cleaning | DroneReach',
    meta: 'Solar panel cleaning for commercial rooftop arrays and solar farms. DroneReach plans methods around panel condition, site access and manufacturer guidance.',
    description: 'Cleaning for commercial arrays and solar farms, guided by the panels and their manufacturer’s requirements.',
    summary: 'Remove surface contamination from commercial solar arrays using a panel-appropriate method.',
    image: image('service-solar', 'rooftop solar panels'),
    benefits: ['Panel-aware methods', 'Manufacturer guidance', 'Array-specific planning'],
    heading: 'Clean panels. A considered method.',
    introduction: 'Dust, bird fouling and other deposits can collect on solar panels. We assess the array, panel condition and site access, then plan cleaning around manufacturer guidance. Commercial rooftops and ground-mounted arrays each need their own approach.',
    checklist: ['Commercial rooftop arrays', 'Ground-mounted arrays', 'Solar farm panels', 'Suitable difficult-access panels'],
    support: 'We do not promise a particular energy-output increase or override manufacturer requirements.',
    buildings: ['solar', 'industrial', 'commercial'],
    faqs: [
      ['Will cleaning improve energy output by a set percentage?', 'We do not promise a percentage increase. Results depend on contamination, panel condition, weather and the system itself; cleaning is not a guarantee of a particular output.'],
      ['How do you choose a cleaning method?', 'We review the panels, manufacturer guidance, surface deposits and access. Water quality, equipment and any restrictions are considered before agreeing the method.'],
      ['Can you clean both rooftop and ground-mounted arrays?', 'We assess both types of site. Suitability depends on the layout, access, surroundings, panel condition and proposed approach.'],
      ['Will my array need to be isolated?', 'Any electrical safety and isolation arrangements must be confirmed with the responsible site operator or qualified specialist as part of planning.'],
    ],
  },
  {
    slug: 'render-cleaning', title: 'Render cleaning', seoTitle: 'Building Render Cleaning | DroneReach',
    meta: 'Assessment-led render cleaning for building exteriors affected by organic growth and staining. DroneReach selects methods to suit the render and its condition.',
    description: 'Targeted cleaning for rendered exteriors affected by organic growth and surface staining.',
    summary: 'A condition-led approach to organic growth and staining on rendered elevations.',
    image: image('service-render', 'textured cream render and exterior windows'),
    benefits: ['Render assessed first', 'Targeted growth treatment', 'Condition-led cleaning'],
    heading: 'Refresh render with care.',
    introduction: 'Algae and other organic growth can leave visible marks on rendered elevations. We identify the render type, inspect its condition and consider the cause of staining before selecting a suitable cleaning method for your building.',
    checklist: ['Rendered façades', 'Organic surface growth', 'Stained elevations', 'Hard-to-reach render areas'],
    support: 'Cracked, loose or failing render may need repairs before cleaning is appropriate.',
    buildings: ['render', 'commercial', 'retail'],
    faqs: [
      ['Can you clean every type of render?', 'Different render systems need different care. We assess the type, finish, condition and available product guidance before confirming suitability.'],
      ['Do you use high pressure on render?', 'We do not assume high pressure is suitable. The proposed method must match the render and its condition, with a test area where needed.'],
      ['Will all staining disappear?', 'Some staining may be persistent or linked to moisture, material deterioration or other underlying issues. We discuss likely results and limitations before work.'],
      ['What happens if the render is cracked?', 'Cracks, loose areas and other defects may need repair or specialist assessment first. Cleaning is not a substitute for addressing those problems.'],
    ],
  },
  {
    slug: 'shopfront-signage-cleaning', title: 'Shopfront & signage cleaning', seoTitle: 'Shopfront & Signage Cleaning | DroneReach',
    meta: 'Cleaning for retail façades, external glazing, fascia panels and signage, including larger retail units and shopping centres. Discuss your site with DroneReach.',
    description: 'Exterior cleaning for retail façades, glazing, fascia panels and external signage.',
    summary: 'A material-aware clean for shopfronts, larger retail units, shopping centres and external signs.',
    image: image('service-signage', 'commercial shopfront fascia and signage'),
    benefits: ['Retail-aware scheduling', 'Mixed-material care', 'Clear access planning'],
    heading: 'A well-presented welcome.',
    introduction: 'Shopfronts combine glass, fascia panels, sign finishes and other exterior materials. We assess each area and plan cleaning around customer access, trading hours and nearby businesses, including larger retail units and shopping centres.',
    checklist: ['Retail exterior glazing', 'Fascia panels', 'External signage', 'Shopping-centre façades'],
    support: 'Illuminated signs, electrical components and delicate finishes need particular attention.',
    buildings: ['retail', 'glazing', 'commercial'],
    faqs: [
      ['Can cleaning take place outside trading hours?', 'Tell us your preferred timescale and operating hours. We discuss practical timing and any restrictions during planning rather than promising a fixed schedule.'],
      ['Can you clean illuminated signage?', 'We assess the sign, its condition and electrical components first. Isolation or specialist advice may be needed, and some signs will not suit the proposed method.'],
      ['Do you work on larger retail units and shopping centres?', 'We can assess larger retail exteriors as well as individual shopfronts. Site layout, occupied areas and access requirements shape the plan.'],
      ['How are customers and neighbouring units protected?', 'The plan sets out exclusion zones, access arrangements and coordination with site management before work begins.'],
    ],
  },
  {
    slug: 'heritage-building-cleaning', title: 'Heritage building cleaning', seoTitle: 'Heritage Building Cleaning | DroneReach',
    meta: 'A cautious, assessment-led approach to historic building exteriors. DroneReach reviews materials, condition, specialist advice and consent before proposing cleaning.',
    description: 'A cautious, assessment-led approach to historic façades and sensitive building materials.',
    summary: 'Historic exteriors assessed carefully, with specialist advice or consent considered where needed.',
    image: image('service-roof', 'traditional stone building with a slate roof and stone chimney'),
    benefits: ['Assessment before action', 'Material-sensitive planning', 'Consent considered'],
    heading: 'Understand the building before cleaning it.',
    introduction: 'Historic façades need care that reflects their materials, condition and significance. We begin with assessment and discuss where specialist advice, test areas or consent may be needed. Drone cleaning is not appropriate for every heritage building.',
    checklist: ['Historic exterior elevations', 'Traditional stone façades', 'Sensitive material assessments', 'Access and consent planning'],
    support: 'We do not claim conservation accreditation. Specialist input may be needed before a cleaning method can be agreed.',
    buildings: ['heritage', 'commercial', 'render'],
    faqs: [
      ['Is drone cleaning suitable for listed buildings?', 'Not automatically. The materials, condition, significance and proposed method need assessment. Consent or specialist advice may be required before any work.'],
      ['Do I need permission before cleaning?', 'Requirements depend on the building and the proposed work. You may need to consult the relevant authority or a qualified adviser, particularly for a listed building.'],
      ['Can you clean fragile stone or historic finishes?', 'Sensitive or deteriorating materials may not suit drone cleaning. Specialist assessment and a carefully agreed test area may be necessary, or a different method may be recommended.'],
      ['Do you provide conservation expertise?', 'We do not claim conservation accreditation or specialist conservation expertise. Where that input is needed, it should be provided by an appropriately qualified specialist before proceeding.'],
      ['What should I send for an initial discussion?', 'Share the location, building status if known, photos, materials and any existing surveys or restrictions. These details help identify what assessment is needed.'],
    ],
  },
].map(service => ({ ...service, href: `/services/${service.slug}` }));
